version: '3.4'

services:
  firapiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  sosreqqueueapiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  sosrequestsapiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  usersapiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

